# Generated by Django 3.1.4 on 2021-03-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.CharField(max_length=1024),
        ),
    ]
