# Generated by Django 3.1.4 on 2021-03-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210324_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(upload_to='')),
                ('expiration_date', models.DateField(blank=True)),
                ('url', models.URLField()),
                ('level', models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-modified_date']},
        ),
    ]
