# Generated by Django 3.1.4 on 2021-04-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210325_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-level']},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='icon',
        ),
        migrations.AddField(
            model_name='certification',
            name='badge',
            field=models.ImageField(blank=True, upload_to='certs'),
        ),
    ]
