# Generated by Django 3.1.4 on 2021-04-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
