# Generated by Django 3.1.4 on 2021-04-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_statement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
